basePath: /
definitions:
  dto.LoginReq:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
host: localhost:8080
info:
  contact: {}
  description: Zev Go Backend API documentation
  title: Zev API
  version: "1.0"
paths:
  /api/ping:
    get:
      description: 测试服务是否正常运行
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Ping
      tags:
      - 测试
  /api/system/login:
    post:
      consumes:
      - application/json
      description: 使用账号密码登录
      parameters:
      - description: 登录信息
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/dto.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 用户登录
      tags:
      - 系统管理-用户
swagger: "2.0"
