// Code generated by swagger.AutoUpdate; DO NOT EDIT.
package swagger

import (
	pkg0 "zev-go/modules/system/entity"
)

var (
	_ pkg0.User
)


// DummyCreate0
// @Summary 创建系统管理-用户
// @Description 创建记录
// @Tags 系统管理-用户
// @Accept json
// @Produce json
// @Param req body pkg0.User true "请求体"
// @Success 200 {object} map[string]interface{}
// @Router /api/system/user/create [post]
func DummyCreate0() {}

// DummyUpdate0
// @Summary 更新系统管理-用户
// @Description 更新记录
// @Tags 系统管理-用户
// @Accept json
// @Produce json
// @Param req body pkg0.User true "请求体"
// @Success 200 {object} map[string]interface{}
// @Router /api/system/user/update [put]
func DummyUpdate0() {}

// DummyDelete0
// @Summary 删除系统管理-用户
// @Description 根据ID删除记录
// @Tags 系统管理-用户
// @Accept json
// @Produce json
// @Param id path string true "ID"
// @Success 200 {object} map[string]interface{}
// @Router /api/system/user/delete/{id} [delete]
func DummyDelete0() {}

// DummyGet0
// @Summary 获取系统管理-用户详情
// @Description 获取单条记录详情
// @Tags 系统管理-用户
// @Accept json
// @Produce json
// @Param id path string true "ID"
// @Success 200 {object} map[string]interface{}
// @Router /api/system/user/get/{id} [get]
func DummyGet0() {}

// DummyList0
// @Summary 获取系统管理-用户列表
// @Description 获取分页列表
// @Tags 系统管理-用户
// @Accept json
// @Produce json
// @Success 200 {object} map[string]interface{}
// @Router /api/system/user/list [get]
func DummyList0() {}
