package swagger

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strings"
)

// crudInfo 保存了用于生成 Swagger 文档的 CRUD 实体及路由元数据。
type crudInfo struct {
	Tag       string // Swagger 分类标签名称 (例如："系统管理-用户")
	BasePath  string // API 路由的基础路径前缀 (例如："/api/system/user")
	PkgPath   string // 实体模型对应的 Go 包路径，用于生成 import 语句 (例如："zev-go/modules/system/entity")
	ModelName string // 实体模型的结构体名称 (例如："User")
}

// crudRegistry 存储所有已注册的 CRUD 实体配置，作为代码生成的数据源。
var crudRegistry []crudInfo


// Init 自动通过 AST 静态扫描项目源码找出所有带有 swagger_tag 标签的模型，并构建 Swagger 文档
func Init() {
	slog.Info("正在扫描模块模型以生成 Swagger 文档...")
	crudRegistry = nil

	fset := token.NewFileSet()
	// 扫描项目中的 modules 目录
	err := filepath.Walk("modules", func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() || !strings.HasSuffix(path, ".go") {
			return nil
		}

		// 解析文件
		fileAst, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			return nil
		}

		ast.Inspect(fileAst, func(n ast.Node) bool {
			// 找 type 声明
			typeSpec, ok := n.(*ast.TypeSpec)
			if !ok {
				return true
			}
			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				return true
			}

			modelName := typeSpec.Name.Name
			var tag, basePath string

			// 检查 struct 内部字段的 tag
			for _, field := range structType.Fields.List {
				if field.Tag != nil {
					tagVal := field.Tag.Value
					if strings.Contains(tagVal, "swagger_tag") {
						tag = extractTagValue(tagVal, "swagger_tag")
					}
					if strings.Contains(tagVal, "swagger_path") {
						basePath = extractTagValue(tagVal, "swagger_path")
					}
				}
			}

			// 只有找到了我们约定的 swagger 标签才注册
			if tag != "" || basePath != "" {
				if tag == "" {
					tag = modelName
				}
				if basePath == "" {
					basePath = "/api/auto/" + strings.ToLower(modelName)
				}

				// 计算出包路径，如: zev-go/modules/system/entity
				modPath := "zev-go/" + filepath.ToSlash(filepath.Dir(path))

				crudRegistry = append(crudRegistry, crudInfo{
					Tag:       tag,
					BasePath:  basePath,
					PkgPath:   modPath,
					ModelName: modelName,
				})
			}
			return true
		})
		return nil
	})

	if err != nil {
		slog.Error("扫描源码出错", "err", err)
	}

	// 1. 根据注册的 CRUD 动态生成 swagger 扫描文件
	generateCrudSwagger()

	// 2. 使用协程在后台执行 swag init，避免阻塞主程序启动
	go func() {
		cmd := exec.Command("go", "run", "github.com/swaggo/swag/cmd/swag@latest", "init", "--parseDependency", "--parseInternal")

		output, err := cmd.CombinedOutput()
		if err != nil {
			slog.Error("Swagger 文档自动更新失败", "err", err, "output", string(output))
		} else {
			slog.Info("Swagger 文档自动更新成功")
			host := os.Getenv("HTTP_HOST")
			port := os.Getenv("HTTP_PORT")
			if host == "" {
				host = "localhost"
			}
			if port == "" {
				port = "8080"
			}
			slog.Info("Swagger 地址", "url", fmt.Sprintf("%s:%s/swagger/index.html", host, port))
		}
	}()
}

// extractTagValue 提取 struct tag 中的特定 key 值
func extractTagValue(structTag, key string) string {
	structTag = strings.Trim(structTag, "`")
	return reflect.StructTag(structTag).Get(key)
}

// generateCrudSwagger 根据 crudRegistry 注册的信息，动态生成包含标准 swaggo 注释的 Go 伪代码文件。
// 生成的文件将被写入 "pkg/swagger/docs_crud_generated.go"，它声明了一系列 dummy 函数，
// 目的是向 swaggo/swag 静态扫描工具暴露泛型控制器在不同实体下对应的实际接口、请求体和路由地址。
func generateCrudSwagger() {
	var sb strings.Builder
	sb.WriteString("// Code generated by swagger.AutoUpdate; DO NOT EDIT.\n")
	sb.WriteString("package swagger\n\nimport (\n")

	// 始终引入 response 包（具名 import），以便 swaggo 能解析注释中的 response.Response / response.PageData 类型
	sb.WriteString("\tresponse \"zev-go/pkg/response\"\n")

	// 收集需要 import 的包并分配别名，以防同名冲突或导入失效
	pkgMap := make(map[string]string)
	idx := 0
	for _, info := range crudRegistry {
		if _, ok := pkgMap[info.PkgPath]; !ok && info.PkgPath != "" {
			pkgMap[info.PkgPath] = fmt.Sprintf("pkg%d", idx)
			idx++
		}
	}

	for pkg, alias := range pkgMap {
		sb.WriteString(fmt.Sprintf("\t%s \"%s\"\n", alias, pkg))
	}
	sb.WriteString(")\n\n")

	// 声明 dummy 变量，以避免 Go 编译器报“导入未使用的包”编译错误
	sb.WriteString("var (\n")
	// 引用 response 包中的类型，防止编译器报"imported and not used"
	sb.WriteString("\t_ response.Response\n")
	for _, info := range crudRegistry {
		if info.PkgPath != "" {
			alias := pkgMap[info.PkgPath]
			sb.WriteString(fmt.Sprintf("\t_ %s.%s\n", alias, info.ModelName))
		}
	}
	sb.WriteString(")\n\n")

	// 为每个注册的 CRUD 路由生成 5 个基本的 HTTP 接口 Dummy 函数 (Create, Update, Delete, Get, List)
	for i, info := range crudRegistry {
		alias := pkgMap[info.PkgPath]
		fullModel := fmt.Sprintf("%s.%s", alias, info.ModelName)
		if info.PkgPath == "" {
			fullModel = info.ModelName
		}

		// 1. 创建 (POST /create) — 返回 response.Response{data: <Entity>}
		sb.WriteString(fmt.Sprintf(`
// DummyCreate%d
// @Summary 创建%s
// @Description 创建记录
// @Tags %s
// @Accept json
// @Produce json
// @Security Bearer
// @Param req body %s true "请求体"
// @Success 200 {object} response.Response{data=%s} "成功"
// @Router %s/create [post]
func DummyCreate%d() {}
`, i, info.Tag, info.Tag, fullModel, fullModel, info.BasePath, i))

		// 2. 更新 (PUT /update) — 只返回 response.Response（无 data 实体）
		sb.WriteString(fmt.Sprintf(`
// DummyUpdate%d
// @Summary 更新%s
// @Description 更新记录
// @Tags %s
// @Accept json
// @Produce json
// @Security Bearer
// @Param req body %s true "请求体"
// @Success 200 {object} response.Response "成功"
// @Router %s/update [put]
func DummyUpdate%d() {}
`, i, info.Tag, info.Tag, fullModel, info.BasePath, i))

		// 3. 删除 (DELETE /delete/:id) — 只返回 response.Response
		sb.WriteString(fmt.Sprintf(`
// DummyDelete%d
// @Summary 删除%s
// @Description 根据ID删除记录
// @Tags %s
// @Accept json
// @Produce json
// @Security Bearer
// @Param id path string true "ID"
// @Success 200 {object} response.Response "成功"
// @Router %s/delete/{id} [delete]
func DummyDelete%d() {}
`, i, info.Tag, info.Tag, info.BasePath, i))

		// 4. 获取详情 (GET /get/:id) — 返回 response.Response{data: <Entity>}
		sb.WriteString(fmt.Sprintf(`
// DummyGet%d
// @Summary 获取%s详情
// @Description 获取单条记录详情
// @Tags %s
// @Accept json
// @Produce json
// @Security Bearer
// @Param id path string true "ID"
// @Success 200 {object} response.Response{data=%s} "成功"
// @Router %s/get/{id} [get]
func DummyGet%d() {}
`, i, info.Tag, info.Tag, fullModel, info.BasePath, i))

		// 5. 分页列表 (GET /list) — 返回 response.Response{data: response.PageData{list: []<Entity>}}
		sb.WriteString(fmt.Sprintf(`
// DummyList%d
// @Summary 获取%s列表
// @Description 获取分页列表
// @Tags %s
// @Accept json
// @Produce json
// @Security Bearer
// @Success 200 {object} response.Response{data=response.PageData{list=[]%s}} "成功"
// @Router %s/list [get]
func DummyList%d() {}
`, i, info.Tag, info.Tag, fullModel, info.BasePath, i))
	}

	os.WriteFile("pkg/swagger/docs_crud_generated.go", []byte(sb.String()), 0644)
}


