package swagger

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"reflect"
	"strings"
)

// crudInfo 保存了用于生成 Swagger 文档的 CRUD 实体及路由元数据。
type crudInfo struct {
	Tag       string // Swagger 分类标签名称 (例如："系统管理-用户")
	BasePath  string // API 路由的基础路径前缀 (例如："/api/system/user")
	PkgPath   string // 实体模型对应的 Go 包路径，用于生成 import 语句 (例如："zev-go/modules/system/entity")
	ModelName string // 实体模型的结构体名称 (例如："User")
}

// crudRegistry 存储所有已注册的 CRUD 实体配置，作为代码生成的数据源。
var crudRegistry []crudInfo

// RegisterCRUD 将一个业务实体及其 API 路径注册到 Swagger 自动生成器中。
// 参数说明：
//   - tag: 对应 Swagger 文档中的 @Tags，对接口进行分组归类
//   - basePath: 对应 API 接口的基础前缀，例如 "/api/system/user"，该函数会自动拼接出 /create, /update, /delete/:id 等子路由
//   - model: 具体的实体结构体对象或其指针 (例如 entity.User{})，本函数将利用反射解析其类型名称和包导入路径
//
// 示例:
//
//	swagger.RegisterCRUD("系统管理-用户", "/api/system/user", entity.User{})
func RegisterCRUD(tag, basePath string, model any) {
	t := reflect.TypeOf(model)
	if t.Kind() == reflect.Ptr {
		t = t.Elem()
	}
	crudRegistry = append(crudRegistry, crudInfo{
		Tag:       tag,
		BasePath:  basePath,
		PkgPath:   t.PkgPath(),
		ModelName: t.Name(),
	})
}

// generateCrudSwagger 根据 crudRegistry 注册的信息，动态生成包含标准 swaggo 注释的 Go 伪代码文件。
// 生成的文件将被写入 "pkg/swagger/docs_crud_generated.go"，它声明了一系列 dummy 函数，
// 目的是向 swaggo/swag 静态扫描工具暴露泛型控制器在不同实体下对应的实际接口、请求体和路由地址。
func generateCrudSwagger() {
	var sb strings.Builder
	sb.WriteString("// Code generated by swagger.AutoUpdate; DO NOT EDIT.\n")
	sb.WriteString("package swagger\n\nimport (\n")

	// 始终引入 response 包（具名 import），以便 swaggo 能解析注释中的 response.Response / response.PageData 类型
	sb.WriteString("\tresponse \"zev-go/pkg/response\"\n")

	// 收集需要 import 的包并分配别名，以防同名冲突或导入失效
	pkgMap := make(map[string]string)
	idx := 0
	for _, info := range crudRegistry {
		if _, ok := pkgMap[info.PkgPath]; !ok && info.PkgPath != "" {
			pkgMap[info.PkgPath] = fmt.Sprintf("pkg%d", idx)
			idx++
		}
	}

	for pkg, alias := range pkgMap {
		sb.WriteString(fmt.Sprintf("\t%s \"%s\"\n", alias, pkg))
	}
	sb.WriteString(")\n\n")

	// 声明 dummy 变量，以避免 Go 编译器报“导入未使用的包”编译错误
	sb.WriteString("var (\n")
	// 引用 response 包中的类型，防止编译器报"imported and not used"
	sb.WriteString("\t_ response.Response\n")
	for _, info := range crudRegistry {
		if info.PkgPath != "" {
			alias := pkgMap[info.PkgPath]
			sb.WriteString(fmt.Sprintf("\t_ %s.%s\n", alias, info.ModelName))
		}
	}
	sb.WriteString(")\n\n")

	// 为每个注册的 CRUD 路由生成 5 个基本的 HTTP 接口 Dummy 函数 (Create, Update, Delete, Get, List)
	for i, info := range crudRegistry {
		alias := pkgMap[info.PkgPath]
		fullModel := fmt.Sprintf("%s.%s", alias, info.ModelName)
		if info.PkgPath == "" {
			fullModel = info.ModelName
		}

		// 1. 创建 (POST /create) — 返回 response.Response{data: <Entity>}
		sb.WriteString(fmt.Sprintf(`
// DummyCreate%d
// @Summary 创建%s
// @Description 创建记录
// @Tags %s
// @Accept json
// @Produce json
// @Param req body %s true "请求体"
// @Success 200 {object} response.Response{data=%s} "成功"
// @Router %s/create [post]
func DummyCreate%d() {}
`, i, info.Tag, info.Tag, fullModel, fullModel, info.BasePath, i))

		// 2. 更新 (PUT /update) — 只返回 response.Response（无 data 实体）
		sb.WriteString(fmt.Sprintf(`
// DummyUpdate%d
// @Summary 更新%s
// @Description 更新记录
// @Tags %s
// @Accept json
// @Produce json
// @Param req body %s true "请求体"
// @Success 200 {object} response.Response "成功"
// @Router %s/update [put]
func DummyUpdate%d() {}
`, i, info.Tag, info.Tag, fullModel, info.BasePath, i))

		// 3. 删除 (DELETE /delete/:id) — 只返回 response.Response
		sb.WriteString(fmt.Sprintf(`
// DummyDelete%d
// @Summary 删除%s
// @Description 根据ID删除记录
// @Tags %s
// @Accept json
// @Produce json
// @Param id path string true "ID"
// @Success 200 {object} response.Response "成功"
// @Router %s/delete/{id} [delete]
func DummyDelete%d() {}
`, i, info.Tag, info.Tag, info.BasePath, i))

		// 4. 获取详情 (GET /get/:id) — 返回 response.Response{data: <Entity>}
		sb.WriteString(fmt.Sprintf(`
// DummyGet%d
// @Summary 获取%s详情
// @Description 获取单条记录详情
// @Tags %s
// @Accept json
// @Produce json
// @Param id path string true "ID"
// @Success 200 {object} response.Response{data=%s} "成功"
// @Router %s/get/{id} [get]
func DummyGet%d() {}
`, i, info.Tag, info.Tag, fullModel, info.BasePath, i))

		// 5. 分页列表 (GET /list) — 返回 response.Response{data: response.PageData{list: []<Entity>}}
		sb.WriteString(fmt.Sprintf(`
// DummyList%d
// @Summary 获取%s列表
// @Description 获取分页列表
// @Tags %s
// @Accept json
// @Produce json
// @Success 200 {object} response.Response{data=response.PageData{list=[]%s}} "成功"
// @Router %s/list [get]
func DummyList%d() {}
`, i, info.Tag, info.Tag, fullModel, info.BasePath, i))
	}

	os.WriteFile("pkg/swagger/docs_crud_generated.go", []byte(sb.String()), 0644)
}

// AutoUpdate 触发自动生成 Swagger 辅助文件并在后台运行 swag 编译工具。
// 流程如下：
//  1. 调用 generateCrudSwagger() 生成包含所有 dummy 函数注释的 docs_crud_generated.go 文件。
//  2. 启动一个 Goroutine 异步执行 "go run github.com/swaggo/swag/cmd/swag@latest init" 命令，
//     以便在不阻塞主服务启动的前提下，重新分析并构建项目最新的 Swagger API JSON/YAML 定义资产。
func AutoUpdate() {
	log.Println("正在生成 Swagger 文档...")

	// 1. 根据注册的 CRUD 动态生成 swagger 扫描文件
	generateCrudSwagger()

	// 2. 使用协程在后台执行 swag init，避免阻塞主程序启动
	go func() {
		cmd := exec.Command("go", "run", "github.com/swaggo/swag/cmd/swag@latest", "init", "--parseDependency", "--parseInternal")

		output, err := cmd.CombinedOutput()
		if err != nil {
			log.Printf("Swagger 文档自动更新失败: %v\n%s", err, string(output))
		} else {
			log.Println("Swagger 文档自动更新成功")
			host := os.Getenv("HTTP_HOST")
			port := os.Getenv("HTTP_PORT")
			if host == "" {
				host = "localhost"
			}
			if port == "" {
				port = "8080"
			}
			log.Printf("Swagger 地址: %s:%s/swagger/index.html", host, port)
		}
	}()
}
