package swagger

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"reflect"
	"strings"
)

type crudInfo struct {
	Tag       string
	BasePath  string
	PkgPath   string
	ModelName string
}

var crudRegistry []crudInfo

// RegisterCRUD 注册 CRUD 接口，以便自动生成 Swagger 文档
// 示例: swagger.RegisterCRUD("系统管理-用户", "/api/system/user", entity.User{})
func RegisterCRUD(tag, basePath string, model any) {
	t := reflect.TypeOf(model)
	if t.Kind() == reflect.Ptr {
		t = t.Elem()
	}
	crudRegistry = append(crudRegistry, crudInfo{
		Tag:       tag,
		BasePath:  basePath,
		PkgPath:   t.PkgPath(),
		ModelName: t.Name(),
	})
}

// generateCrudSwagger 动态生成一个带注释的 Go 文件供 swaggo 扫描
func generateCrudSwagger() {
	var sb strings.Builder
	sb.WriteString("// Code generated by swagger.AutoUpdate; DO NOT EDIT.\n")
	sb.WriteString("package swagger\n\nimport (\n")

	// 收集需要 import 的包
	pkgMap := make(map[string]string)
	idx := 0
	for _, info := range crudRegistry {
		if _, ok := pkgMap[info.PkgPath]; !ok && info.PkgPath != "" {
			pkgMap[info.PkgPath] = fmt.Sprintf("pkg%d", idx)
			idx++
		}
	}

	for pkg, alias := range pkgMap {
		sb.WriteString(fmt.Sprintf("\t%s \"%s\"\n", alias, pkg))
	}
	sb.WriteString(")\n\n")

	// 声明 dummy 变量防止未使用包报错
	sb.WriteString("var (\n")
	for _, info := range crudRegistry {
		if info.PkgPath != "" {
			alias := pkgMap[info.PkgPath]
			sb.WriteString(fmt.Sprintf("\t_ %s.%s\n", alias, info.ModelName))
		}
	}
	sb.WriteString(")\n\n")

	for i, info := range crudRegistry {
		alias := pkgMap[info.PkgPath]
		fullModel := fmt.Sprintf("%s.%s", alias, info.ModelName)
		if info.PkgPath == "" {
			fullModel = info.ModelName
		}

		sb.WriteString(fmt.Sprintf(`
// DummyCreate%d
// @Summary 创建%s
// @Description 创建记录
// @Tags %s
// @Accept json
// @Produce json
// @Param req body %s true "请求体"
// @Success 200 {object} map[string]interface{}
// @Router %s/create [post]
func DummyCreate%d() {}
`, i, info.Tag, info.Tag, fullModel, info.BasePath, i))

		sb.WriteString(fmt.Sprintf(`
// DummyUpdate%d
// @Summary 更新%s
// @Description 更新记录
// @Tags %s
// @Accept json
// @Produce json
// @Param req body %s true "请求体"
// @Success 200 {object} map[string]interface{}
// @Router %s/update [put]
func DummyUpdate%d() {}
`, i, info.Tag, info.Tag, fullModel, info.BasePath, i))

		sb.WriteString(fmt.Sprintf(`
// DummyDelete%d
// @Summary 删除%s
// @Description 根据ID删除记录
// @Tags %s
// @Accept json
// @Produce json
// @Param id path string true "ID"
// @Success 200 {object} map[string]interface{}
// @Router %s/delete/{id} [delete]
func DummyDelete%d() {}
`, i, info.Tag, info.Tag, info.BasePath, i))

		sb.WriteString(fmt.Sprintf(`
// DummyGet%d
// @Summary 获取%s详情
// @Description 获取单条记录详情
// @Tags %s
// @Accept json
// @Produce json
// @Param id path string true "ID"
// @Success 200 {object} map[string]interface{}
// @Router %s/get/{id} [get]
func DummyGet%d() {}
`, i, info.Tag, info.Tag, info.BasePath, i))

		sb.WriteString(fmt.Sprintf(`
// DummyList%d
// @Summary 获取%s列表
// @Description 获取分页列表
// @Tags %s
// @Accept json
// @Produce json
// @Success 200 {object} map[string]interface{}
// @Router %s/list [get]
func DummyList%d() {}
`, i, info.Tag, info.Tag, info.BasePath, i))
	}

	os.WriteFile("pkg/swagger/docs_crud_generated.go", []byte(sb.String()), 0644)
}

// AutoUpdate 自动在后台更新 Swagger 文档
func AutoUpdate() {
	log.Println("正在生成 Swagger 文档...")

	// 1. 根据注册的 CRUD 动态生成 swagger 扫描文件
	generateCrudSwagger()

	// 2. 使用协程在后台执行 swag init，避免阻塞主程序启动
	go func() {
		cmd := exec.Command("go", "run", "github.com/swaggo/swag/cmd/swag@latest", "init", "--parseDependency", "--parseInternal")
		
		output, err := cmd.CombinedOutput()
		if err != nil {
			log.Printf("Swagger 文档自动更新失败: %v\n%s", err, string(output))
		} else {
			log.Println("Swagger 文档自动更新成功")
		}
	}()
}
