services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: zev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zev
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql
    restart: unless-stopped

volumes:
  db-data:
